### PR TITLE
Correct Relative Image URLs in readme’s

### LINKED ISSUE #85: Relative URLs not working
If a repository has an image with relative URL, Astral tries to load if from the `astralapp.com` domain.

This is one repository that causes problems: https://github.com/cruffenach/CRToast . You can see that in Astral, the screenshots are not showing up.

I am willing to try to open a PR for this if pointed to the right file, as I don't know the project structure, nor Angular or Vue.

### PR DESCRIPTION
**Pull request by alexbowers**
Fixes #85

### CODE REVIEW

**Comment by syropian** [comment]
Looks good! Are you able to merge this into the base repo?

**Comment by alexbowers** [comment]
This is merged in, can you release it?

**Comment by syropian** [comment]
@alexbowers Released on production 🎉

File: resources/assets/js/store/actions.js [hunk 1]
```diff
@@ -88,7 +88,14 @@ export const fetchReadme = ({ dispatch }, name) => {
   const accessToken = ls("access_token")
   const promise = new Promise((resolve, reject) => {
     Vue.http.get(`https://api.github.com/repos/${name}/readme?access_token=${accessToken}`).then((response) => {
-      const readme = Base64.decode(response.data.content)
+      let readme = Base64.decode(response.data.content)
+
+      const branch = response.data.url.split('?ref=')[1]
+      const regex = /(!\[.*\])\(\/?(?!(http:\/\/)|(https:\/\/)|(\/))(.*)\)/igm
```
Comment (revolter) [inline resources/assets/js/store/actions.js]: I personally try to avoid using `.` as it can be evil. Could `\[[^\]]\]` work instead of `\[.*\]`, and `([^)])` instead of `(.*)`? Also, `(https?:\/\/)` instead of `(http:\/\/)|(https:\/\/)`?

**Comment by revolter** [comment]
Works like a charm, thanks a bunch!

File: resources/assets/js/store/actions.js (hunk 1 above)
Comment (alexbowers) [inline resources/assets/js/store/actions.js]: Unfortunately, `\[[^\]]*\]` doesn't work an image alt text in markdown does support square brackets, such as this: `![This [should] Work](https://placekitten.com/200/300)` 

You can see the regex in work here: http://regexr.com/3ecpl

My regex doesn't cover this usecase yet, since I couldn't solve it. The next release to affect the regex should probably try to fix this issue too. I can't see how your solution would work in that way, whereas the solution in use, I think is quite close. Though I haven't been able to solve it.

The `https?` fix I do like.

If you are able to fix the bug above, then I'll get it merged in and released with the better regex. 

Thanks.

Comment (alexbowers) [inline resources/assets/js/store/actions.js]: If your email is different to the above, its because I made a stupid mistake. I tested against a `https` link which obviously doesn't get matched.

Comment (revolter) [inline resources/assets/js/store/actions.js]: Wow, didn't know that, I thought it doesn't support nested square brackets. Sorry!

> The next release to affect the regex should probably try to fix this issue too.

I don't understand this part.

> If you are able to fix the bug above, then I'll get it merged in and released with the better regex.

You mean to open a PR with the `https?` part?

Comment (alexbowers) [inline resources/assets/js/store/actions.js]: An example repository: https://github.com/alexbowers/readme-testing/blob/master/README.md

Comment (alexbowers) [inline resources/assets/js/store/actions.js]: > Wow, didn't know that, I thought it doesn't support nested square brackets. Sorry!

No problem.

> I don't understand this part.

I'll do another release to improve this regex at some point. If you can think of a solution  that does not use `.*` for the left hand side, but allows nested square brackets, then i'm all  ears to include that. Otherwise i'll do a release with just the `https?` bit

> You mean to open a PR with the https? part?

If you wish to get the credit for it, then you can open it. (If your taking part in HacktoberFest, you may want to do this).

If you don't want to get the whole environment setup locally, then I can do it.

Comment (revolter) [inline resources/assets/js/store/actions.js]: > If you can think of a solution that does not use `.*` for the left hand side

I'll think of one and let you know.

> If you wish to get the credit for it

Oh, I don't want credit for it. And, regarding Hacktoberfest, [I'm covered](https://hacktoberfestchecker.herokuapp.com/?username=Revolter) 😄

Comment (revolter) [inline resources/assets/js/store/actions.js]: Take a look at [this][1]. It matches anything that isn't followed by `](`, with variable number of spaces between them, as `![alt] (url)` is valid too. It looks like it matches

    ![alt]
    (url)

which, curiously, is valid too.

It also stops capturing groups that are not used, so it can use `$1` and `$2` in the replace instead of `$5`.

  [1]: (!\[.*\])\(\/?(?!(http:\/\/)|(https:\/\/)|(\/))(.*)\)

Comment (alexbowers) [inline resources/assets/js/store/actions.js]: > Oh, I don't want credit for it. And, regarding Hacktoberfest, 

https://hacktoberfestchecker.herokuapp.com/?username=alexbowers

Maybe i'll submit it ;)

Comment (revolter) [inline resources/assets/js/store/actions.js]: > Maybe i'll submit it

For sure!

**Comment by syropian** [comment]
@alexbowers I noticed some image paths specifically use `./` to ensure they're in the root dir. Those paths seem to still fail in Astral.

**Comment by revolter** [comment]
@syropian, Actually, the URL in the README is `./media/evajs.png`, because that's what the code receives. And more so, it's HTML :(

    

which the regex doesn't handle at all. Instead, it searches for markdown like `alt`.

**Comment by alexbowers** [comment]
Thats easy enough to handle, we can check if the first character is either an optional slash, or an optional dotslash ?

**Comment by alexbowers** [comment]
I'll fix this tonight. And i'll also put the https? improvement in there.

**Comment by alexbowers** [comment]
- [ ] https://regex101.com/r/9OCoLx/2
- [ ] https? improvement
- [ ] dotslash improvement

**Comment by revolter** [comment]
Doesn't the first part of the regex be adjusted too? Something like https://regex101.com/r/9OCoLx/3

**Comment by alexbowers** [comment]
To keep it readable, i'm going to have 2 regex replaces. Makes it more maintainable rather than having something crazy complex. But yeah, there will be an img tag matcher

**Comment by revolter** [comment]
Of course, a separate regex is way better. Hope the last regex helps you.
